apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: players
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: deployments/players
    repoURL: https://github.com/claudioed/players-app.git
    targetRevision: open-telemetry
    helm:
      valueFiles:
        - values-kong.yaml
  destination:
    namespace: bets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
